set_property IOSTANDARD LVCMOS33 [get_ports audioEn]
set_property IOSTANDARD LVCMOS33 [get_ports audioOut]
set_property IOSTANDARD LVCMOS33 [get_ports chSel]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports micClk]
set_property IOSTANDARD LVCMOS33 [get_ports micData]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {switches[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_out[0]}]

set_property PACKAGE_PIN D12 [get_ports audioEn]
set_property PACKAGE_PIN R15 [get_ports {switches[3]}]
set_property PACKAGE_PIN M13 [get_ports {switches[2]}]
set_property PACKAGE_PIN L16 [get_ports {switches[1]}]
set_property PACKAGE_PIN J15 [get_ports {switches[0]}]
set_property PACKAGE_PIN A11 [get_ports audioOut]
set_property PACKAGE_PIN F5 [get_ports chSel]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN J5 [get_ports micClk]
set_property PACKAGE_PIN H5 [get_ports micData]
set_property PACKAGE_PIN T10 [get_ports {LED_out[6]}]
set_property PACKAGE_PIN R10 [get_ports {LED_out[5]}]
set_property PACKAGE_PIN K16 [get_ports {LED_out[4]}]
set_property PACKAGE_PIN K13 [get_ports {LED_out[3]}]
set_property PACKAGE_PIN P15 [get_ports {LED_out[2]}]
set_property PACKAGE_PIN T11 [get_ports {LED_out[1]}]
set_property PACKAGE_PIN L18 [get_ports {LED_out[0]}]
set_property PACKAGE_PIN J14 [get_ports {Anode_Activate[3]}]
set_property PACKAGE_PIN T9 [get_ports {Anode_Activate[2]}]
set_property PACKAGE_PIN J18 [get_ports {Anode_Activate[1]}]
set_property PACKAGE_PIN J17 [get_ports {Anode_Activate[0]}]



// Rest Signal
set_property PACKAGE_PIN N17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]

// VGA Port
set_property PACKAGE_PIN D8 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN D7 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN C7 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN B7 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN B6 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN A4 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN B4 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN A3 [get_ports {VGA_R[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]

// Sync Ports
set_property PACKAGE_PIN B11 [get_ports hSync]
set_property PACKAGE_PIN B12 [get_ports vSync]
set_property IOSTANDARD LVCMOS33 [get_ports hSync]
set_property IOSTANDARD LVCMOS33 [get_ports vSync]

// PS2 Stuff
set_property PACKAGE_PIN F4 [get_ports ps2_clk]
set_property PACKAGE_PIN B2 [get_ports ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports ps2_data]